name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

  rubocop:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: |
          bundle exec rubocop --format json --out rubocop_output.json || true
          if [[ $(jq '.summary.offense_count' rubocop_output.json) -gt 0 ]]; then
            echo "RuboCop offenses detected. Failing the job."
            exit 1
          fi

  rspec:
    runs-on: ubuntu-latest
    needs: rubocop
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec
        run: |
          bundle exec rspec --format documentation

  cucumber:
    runs-on: ubuntu-latest
    needs: rspec
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Cucumber
        run: |
          bundle exec cucumber
