name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          bundler-cache: true
      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

  rubocop:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: |
          bundle exec rubocop --format json --out rubocop_output.json || true
          if [[ $(jq '.summary.offense_count' rubocop_output.json) -gt 0 ]]; then
            echo "RuboCop offenses detected. Failing the job."
            exit 1
          fi

  rspec:
    runs-on: ubuntu-latest
    needs: rubocop
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec
        run: |
          bundle exec rspec --format documentation

  cucumber:
    runs-on: ubuntu-latest
    needs: rspec
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Cucumber
        run: |
          bundle exec cucumber
